# Generated by Django 5.0 on 2023-12-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0002_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.CharField(max_length=40, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=60)),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
