# Generated by Django 4.2.7 on 2023-12-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=254, unique=True
            ),
        ),
    ]
