# Generated by Django 4.2.7 on 2023-12-12 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_user_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
